### ISSUE TITLE
Names of texts

### ISSUE THREAD

**Issue by seumasjeltzz** [seumasjeltzz/EasyGreekReaders#3]
So, quite a few of the texts bear a title, either English or Greek.
Is this worth including as the first line of text?

**Comment by jtauber** [comment]
It's the age old question of whether things like titles are metadata or part of the content.

(Ted Nelson once quipped to me that metadata is data you forgot to put in the first time around)

I think if it's in Greek and essentially part of the "story" it's worth including. Of course then we start to get into questions of markup.

**Comment by seumasjeltzz** [comment]
Very rare that they're in Greek. Will take your suggestion for now. 
I tend to have them typed up in my own files, so not a big deal to do something with that later.
